[package]
name = "fedimint-fuzz"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }
publish = false
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "vec"
path = "src/bin/vec.rs"

# cargo-deny just needs at least one `bin` defined
[lib]
name = "fedimint_fuzz"
path = "src/lib.rs"

[dependencies]
fedimint-core = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-meta-common = { workspace = true }
fedimint-mint-common = { workspace = true }
fedimint-wallet-common = { workspace = true }
# needs to be pinned to the same version `cargo-fuzz` binary uses
honggfuzz = { version = "=0.5.56", default-features = false }
